---
- name: Set up HAProxy
  hosts: all
  become: true
  tasks:
    - name: Install packages
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
        update_cache: true
      vars:
        packages:
          - haproxy
          - netcat

    - name: Copy haproxy.cfg
      ansible.builtin.copy:
        src: ./config_files/update-haproxy-cfg.py
        dest: /home/vagrant/update-haproxy-cfg.py
        mode: '0777'
