---
- name: Set up control-plane
  hosts: all
  become: true
  tasks:
    - name: Install packages that allow apt to be used over HTTPS
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
        update_cache: true
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - git
          - gnupg2
          - lsb-release
          - software-properties-common
          - uidmap
          - vim
          - wget

    - name: Add an apt signing key for Docker
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add apt repository for stable version
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install docker and its dependecies
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
        update_cache: true
      vars:
        packages:
          - docker-ce
          - docker-ce-cli
          - containerd.io
      notify:
        - Check docker status

    - name: Add vagrant user to docker group
      ansible.builtin.user:
        name: vagrant
        group: docker

    - name: Remove swapfile from /etc/fstab
      ansible.posix.mount:
        name: "{{ item }}"
        fstype: swap
        state: absent
      with_items:
        - swap
        - none

    - name: Disable swap
      ansible.builtin.command: swapoff -a
      changed_when: ansible_swaptotal_mb == 0
      when: ansible_swaptotal_mb > 0

    - name: Create keyring directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add an apt signing key for Kubernetes
      ansible.builtin.apt_key:
        keyring: /etc/apt/keyrings/kubernetes-archive-keyring.gpg
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Adding apt repository for Kubernetes
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main"
        state: present
        filename: kubernetes

    - name: Install Kubernetes binaries
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
        update_cache: true
      vars:
        packages:
          - kubelet
          - kubeadm
          - kubectl

    - name: Configure node ip # https://github.com/kubernetes/release/pull/672
      ansible.builtin.lineinfile:
        path: /etc/default/kubelet
        line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}
        state: present
        create: true
        mode: '0644'

    - name: Restart kubelet
      ansible.builtin.service:
        name: kubelet
        daemon_reload: true
        state: restarted

    - name: Clear containerd config # https://github.com/containerd/containerd/issues/4581
      ansible.builtin.file:
        path: /etc/containerd/config.toml
        state: absent

    - name: Restart containerd
      ansible.builtin.service:
        name: containerd
        daemon_reload: true
        state: restarted

    - name: Add a line to /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "192.168.50.9 cplb"
        insertafter: EOF

    - name: Save certificate key for other control planes
      ansible.builtin.command: kubeadm init --control-plane-endpoint "cplb:6443" --upload-certs \
                               --apiserver-advertise-address="{{ node_ip }}" --pod-network-cidr=192.168.0.0/16
      register: certificate_key
      changed_when: true # TODO: clean up
      # `--apiserver-advertise-address` is **required** to bind to correct IP.
      # otherwise host-only interface is selected for etcd (10.0.2.15)
      # https://github.com/kubernetes/kubeadm/issues/1359#issuecomment-619564221

    - name: Copy certificate key command to local file
      become: false
      ansible.builtin.copy:
        content: "{{ certificate_key.stdout }}"
        dest: ./certificate
        mode: '0666'
      delegate_to: localhost

    - name: Setup kubeconfig for vagrant user
      ansible.builtin.command: "{{ item }}"
      with_items:
        - mkdir -p /home/vagrant/.kube
        - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
        - chown vagrant:vagrant /home/vagrant/.kube/config
      changed_when: true # TODO: clean up

    - name: Set up autocomplete
      ansible.builtin.lineinfile:
        path: /home/vagrant/.bashrc
        line: "source <(kubectl completion bash)"
        insertafter: EOF

    - name: Install calico operator and CRDs
      become: false
      ansible.builtin.command: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/tigera-operator.yaml
      changed_when: true # TODO: clean up

    - name: Install calico pod network
      become: false
      ansible.builtin.command: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/custom-resources.yaml
      changed_when: true # TODO: clean up

  handlers:
    - name: Check docker status
      ansible.builtin.service:
        name: docker
        state: started
