---
- name: Set up node(s)
  hosts: all
  become: true
  tasks:
    - name: Install packages that allow apt to be used over HTTPS
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
        update_cache: true
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg2
          - software-properties-common

    - name: Add an apt signing key for Docker
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add apt repository for stable version
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install docker and its dependecies
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
        update_cache: true
      vars:
        packages:
          - docker-ce
          - docker-ce-cli
          - containerd.io
      notify:
        - Check docker status

    - name: Add vagrant user to docker group
      ansible.builtin.user:
        name: vagrant
        group: docker

    - name: Remove swapfile from /etc/fstab
      ansible.posix.mount:
        name: "{{ item }}"
        fstype: swap
        state: absent
      with_items:
        - swap
        - none

    - name: Disable swap
      ansible.builtin.command: swapoff -a
      changed_when: true # TODO: clean up
      when: ansible_swaptotal_mb > 0

    - name: Create keyring directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add an apt signing key for Kubernetes
      ansible.builtin.apt_key:
        keyring: /etc/apt/keyrings/kubernetes-archive-keyring.gpg
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Adding apt repository for Kubernetes
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main"
        state: present
        filename: kubernetes

    - name: Install Kubernetes binaries
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
        update_cache: true
      vars:
        packages:
          - kubelet=1.18.6-00
          - kubeadm=1.18.6-00
          - kubectl=1.18.6-00

    - name: Configure node ip # https://github.com/kubernetes/release/pull/672
      ansible.builtin.lineinfile:
        path: /etc/default/kubelet
        line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}
        state: present
        create: true
        mode: '0644'

    - name: Restart kubelet
      ansible.builtin.service:
        name: kubelet
        daemon_reload: true
        state: restarted

    - name: Clear containerd config # https://github.com/containerd/containerd/issues/4581
      ansible.builtin.file:
        path: /etc/containerd/config.toml
        state: absent

    - name: Restart containerd
      ansible.builtin.service:
        name: containerd
        daemon_reload: true
        state: restarted

    - name: Copy the certificate key to server location
      become: false
      ansible.builtin.copy:
        src: certificate
        dest: /tmp/certificate.txt
        mode: '0666'

    - name: Copy join command
      ansible.builtin.shell:
        cmd: |
          grep "join any number of worker nodes" /tmp/certificate.txt -A 3 | tail -2 \
          > /tmp/join-command.sh && chmod 777 /tmp/join-command.sh
      # TODO: figure out pipefail linter msg because `set -o pipefail` causes command to fail
      tags:
        - skip_ansible_lint

    - name: Add a line to /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "192.168.50.9 cplb"
        insertafter: EOF

    - name: Join the node to cluster
      ansible.builtin.script:
        cmd: /tmp/join-command.sh

  handlers:
    - name: Check docker status
      ansible.builtin.service:
        name: docker
        state: started
