---
- name: Set up high availability control-plane
  hosts: all
  become: true
  tasks:
    - name: Copy the init output to server location
      become: false
      ansible.builtin.copy:
        src: ./init-output
        dest: /tmp/init-output
        mode: '0666'

    - name: Copy and modify join command
      ansible.builtin.shell:
        cmd: |
          grep "join any number of the control-plane node" /tmp/init-output -A 4 | tail -3 \
          | echo "$(cat -) --apiserver-advertise-address=\"{{ node_ip }}\"" \
          > /tmp/join-command.sh && chmod 777 /tmp/join-command.sh
      # `--apiserver-advertise-address` is **required** to bind to correct IP.
      # otherwise host-only interface is selected for etcd (10.0.2.15)
      # https://github.com/kubernetes/kubeadm/issues/1359#issuecomment-619564221
      tags:
        - skip_ansible_lint
      # TODO: figure out pipefail linter msg because `set -o pipefail` causes command to fail

    - name: Join the control-plane to cluster
      changed_when: true
      ansible.builtin.command:
        cmd: bash /tmp/join-command.sh
