---
- name: Set up lead control-plane
  hosts: all
  become: true
  tasks:
    - name: Init cluster using control-plane-endpoint
      ansible.builtin.command: kubeadm init --control-plane-endpoint "cp-lb:6443" --upload-certs \
                               --apiserver-advertise-address="{{ node_ip }}" --pod-network-cidr=192.168.0.0/16
      register: init_output
      changed_when: true # TODO: clean up
      # `--apiserver-advertise-address` is **required** to bind to correct IP.
      # otherwise host-only interface is selected for etcd (10.0.2.15)
      # https://github.com/kubernetes/kubeadm/issues/1359#issuecomment-619564221

    - name: Copy init command output to local file
      become: false
      ansible.builtin.copy:
        content: "{{ init_output.stdout }}"
        dest: ./init-output
        mode: '0666'
      delegate_to: localhost

    - name: Setup kubeconfig for vagrant user
      ansible.builtin.command: "{{ item }}"
      with_items:
        - mkdir -p /home/vagrant/.kube
        - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
        - chown -R vagrant:vagrant /home/vagrant/.kube
      changed_when: true # TODO: clean up

    - name: Set up kubectl autocomplete
      ansible.builtin.blockinfile:
        path: /home/vagrant/.bashrc
        block: |
          source <(kubectl completion bash)
          alias k=kubectl
          complete -o default -F __start_kubectl k

    - name: Install calico operator and CRDs
      become: false
      ansible.builtin.command: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v{{ calico_version }}/manifests/tigera-operator.yaml
      changed_when: true # TODO: clean up

    - name: Install calico pod network
      become: false
      ansible.builtin.command: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v{{ calico_version }}/manifests/custom-resources.yaml
      changed_when: true # TODO: clean up
