---
- name: Set up node
  hosts: all
  become: true
  tasks:
    - name: Copy the init output to server location
      become: false
      ansible.builtin.copy:
        src: ./init-output
        dest: /tmp/init-output
        mode: '0666'

    - name: Copy join command
      ansible.builtin.shell:
        cmd: |
          grep "join any number of worker nodes" /tmp/init-output -A 3 | tail -2 \
          > /tmp/join-command.sh && chmod 777 /tmp/join-command.sh
      # TODO: figure out pipefail linter msg because `set -o pipefail` causes command to fail
      tags:
        - skip_ansible_lint

    - name: Join the node to cluster
      changed_when: true
      ansible.builtin.command:
        cmd: bash /tmp/join-command.sh
